### ISSUE TITLE
2.0 module?

### ISSUE THREAD

**Issue by purplefox** [campudus/vertx-session-manager#3]
I'd love to see this module built for 2.0 and in the module registry before we release 2.0 :)

**Comment by Narigo** [comment]
Which version should I build against? Right now it's Vert.x 2.0.0-SNAPSHOT, but there are a few 2.0.0-betaX and 2.0.0-beta4-SNAPSHOT. If there are no more API changes, it wouldn't matter, right?

**Comment by Narigo** [comment]
I used vertxVersion=2.0.0-beta3 now and it should be waiting for approval in the module registry now
