### ISSUE TITLE
No examples provided

### ISSUE THREAD

**Issue by rkrx** [campudus/vertx-session-manager#4]
Please provide an working example to show how to integrate session management with a basic vert.x project. As a vert.x beginner, I have no idea how to bring an application to live with the installation details provided in the README.md.

**Comment by Zwergal** [comment]
Does that help?
http://campudus.com/en/415/vert-x-session-manager-modules/

**Comment by rkrx** [comment]
session-manager-helper-v1.1.0 does not work with vert.x 2.0, right?

**Comment by Narigo** [comment]
Sorry for the late reply here... can't remember that I've seen it before! :(

You really don't need the session manager helper. The session manager helper won't get any more updates and it doesn't really provide too much help. It's only an easier to use abstraction API in Java and Scala for sending/receiving messages to/from the session manager. Please use the session manager directly via the event bus as described in Readme.md and as you use any other module! :)
