### ISSUE TITLE
Share Session In Cluster

### ISSUE THREAD

**Issue by ghost** [campudus/vertx-session-manager#6]
I am starting a new project and a requirement of it is running clustered. I understand this project is using vertx shared data which does not support running a multi server cluster according to this http://vertx.io/core_manual_java.html#shared-data. After going through the source code I am thinking of creating a new class called HazelcastSharedDataSessionStore and rather than using the shared data to access hazelcast directly as per the last answer to this question. http://stackoverflow.com/questions/12299132/clustering-and-shared-data-in-vert-x. Would you be interested in this feature being added and should I do a pull request or are you sticking to only using vert apis?

**Comment by Narigo** [comment]
We've added MongoDB storage to be able to share data across JVM instances, but using Hazelcast directly might be a good addition as well. I'm not sure about what would be needed to add here, though. Do you need to add a new dependency or simliar, to be able to use it? If it would be only needed when using the Hazelcast storage, it should be okay from my side. Just be sure to add tests and check that upgrading this module won't need everyone to add a new runtime dependency... :)

Thanks!

I'm still hoping though that Vert.x 3 provides a way to share data across JVM instances though and we can port it when it gets released...

**Comment by ghost** [comment]
I've also been hoping Vert.x 3 will support this as it would really help. I just need it sooner than that unfortunately. I'll check those items and let you know if it all works as planned. Thanks for the great module.

**Comment by ghost** [comment]
Well after working with it for a bit I can confirm that it is a better idea to wait for Vert.x 3. What I have done requires more libs and upgrading the vert.x version as well as forcing cluster mode to start in order to start Hazelcast. I'm also not able to get all the tests working. I'll have to use mongodb for the time being.

**Comment by Narigo** [comment]
Ok, I'll close it for now.
